CarltonSoftware/plato-js-client

- src/common/PropertyRoom.js
- src/common/RoomType.js
> BP-40/TABS2-5791 feat: add 'visible to customer' to labels

- package-lock.json
- package.json
- src/common/BookingApproval.js
- src/common/OwnerPaymentSelection.js
- src/common/PricePeriod.js
- src/common/Property.js
- src/common/PropertyBranding.js
- src/common/PropertyBrandingPrice.js
Everything seems to be working. Just tagging you all in incase any of your apps have a require('moment') in them without the package in the package.json.
> Convert the js client over to use dayjs

- src/common/TemplateContactMethod.js
- Added multilingual subject handling to TemplateContactMethodEntity.
Related to React Prototype and Plato changes.
> DEV-144 Feat: Multilingual Subject

- src/common/BookingEnquiry.js
-Added agency and owner booking type id to booking enquiry request.
> TABS2-5980 Fix: Agency booking error.

- src/common/ManagedService.js
-Agency/Owner/Supplier Can Provide added to Managed Service form values.
-Changed do not modify to be false if null, as it was causing a "this
must be part of the form" error if the checkbox was unchecked.
> DEV-543 Feat: Added Managed Service Values

- src/common/Template.js
@cdobson this is the change for the plato-js-client
> DEV-377 feat: add new showpotentialreservation and showpotentialhold to booking correspondance templates

- src/common/Actor.js
> DEV-564 Feat: Export Contact Log

- src/common/Actor.js
-Added arrivalreportautosend to sendable Actor fields.
> DEV-438 Feat: Arrivals Auto Report

- src/common/Actor.js
-Updated front end checkbox to send false when not selected.
There are also PRs for Plato and React-Prototype.
> DEV-438 Arrivals Auto Send

- src/common/OwnerPaymentSelection.js
- src/common/OwnerPaymentTerm.js
-Added Owner Payment Terms to create Owner Payment Selection.
> DEV-281 Owner Payment Improvements

- src/common/PropertyOwner.js
- src/common/PropertySupplierService.js
-Added boolean variables to PropertySupplierService and PropertyOwner.
Related PR on react-client.
> DEV-394 Feat: GDPR Request Data

- src/common/Source.js
-Added affiliate to Source JS Object.
--Only shows when updating existing Sources, does not show when creating
a new Source.
Has associated React Prototype pull request.
> DEV-689 Feat: Add Affiliate to Admin/Source

- src/common/TemplateContactMethodTriggerEventFilter.js
-BookingBranding and OwnerBranding
> DEV-1024 Feat: Added new Trigger Event Filters

- src/common/Contact.js
-Added optional fields to Contact.
> DEV-986 Feat: Text substitution permissions.

- src/common/PropertyAnswer.js
- src/common/PropertyQuestion.js
add datefromanswerrequired field and validschema to property question
> DEV-623 feat: add fromdate, todate fields and validschema to property answer

- src/common/Complaint.js
- uncommenting code for the new complaint fields
- adding min 3 char requirements for complaint subject to match note subject min char
> fix/CORE-132: uncommenting code for complaint new fields

- src/common/ComplaintSelectedReason.js
- src/index.js
Has related React-prototype and plato PRs.
> CORE-142 Feat: Multiple Complaint Reasons New Entity

- src/common/Voucher.js
because a complaint is not always passed in
> CORE-209 fix: remove id from complaint check

- src/common/SpecialOfferBranding.js
API changes for the same ticket.
Without this it will fail to add property restrictions on special offers other then amount and fixed types
> feat/RAY-16: adding amount field for fixed and amount special offers

- src/common/SpecialOfferBranding.js
> feat/RAY-16-2: changes for new structure

- src/common/Property.js
Hi @simonf7 and @cdobson 
And same with this one :)
> RAY-229 feat: add currency to proerty price
